CREATE OR REPLACE VIEW  SUPPLY.SUPPLY_DRIVER_INSTALLER.VIEW_NOVO_IQP (

	ORDEM_DE_SERVICO,
	DATA_SERVICO,
	STATUS,
	REPORTE_OK,
	REPORTE_TEMPOHABIL,
	PRESTADOR,
	UF,
	CONSULTOR,
	QTD_INSTALACAO,
	QTD_DESINSTALACAO,
	QTD_VISITA_TECNICA,
	QTD_NECESSIDADE_TESTE,
	QTD_TESTADO,
	SCORE,
	ADERENCIA_TESTES
    
) AS (

WITH 

--- [QUERY - TESTES DOS DISPOSITIVOS - ESN ÚNICO] ---

TESTES AS (
    SELECT DISTINCT
        DEVICE_ID AS ESN,
        START_TIMESTAMP::DATE AS DATA_TESTE
    FROM
        IOT_DB.STAGING.DEVICE_INSTALLATION_AUDIT
),

--- [QUERY - DISPOSITIVOS INSTALADOS > 30/04/2024]

DISPOSITIVOS AS (
    SELECT DISTINCT
        REPLACE(DISP.ORDEM_DE_SERVICO, ' ', '') AS ORDEM_DE_SERVICO,
        E.DATA_AGENDADA::DATE AS DATA_SERVICO,
        DISP.TIPO_SERVICO,
        REPLACE(DISP.ESN, ' ', '') AS ESN
    FROM
        SUPPLY.SUPPLY_DRIVER_INSTALLER.DISPOSITIVOS AS DISP
    LEFT JOIN
        SUPPLY.SUPPLY_DRIVER_INSTALLER.EVENTOS AS E
            ON DISP.ORDEM_DE_SERVICO = E.ORDEM_DE_SERVICO
    WHERE
        E.DATA_AGENDADA >= '2024-05-01'
),

--- [QUERY - DADOS ORDENS DE SERVIÇO > 30/04/2024]

ORDENS AS (
    SELECT DISTINCT
        REPLACE(O.ORDEM_DE_SERVICO, ' ', '') AS ORDEM_DE_SERVICO,
        O.ORDEM_DE_SERVICO || '_' || P.NOME AS ID_AGENDAMENTO,
        E.DATA_AGENDADA::DATE AS DATA_SERVICO,
        CASE
            WHEN O.STATUS_REPORT IS NULL THEN 'SIM'
            ELSE O.STATUS_REPORT
        END AS REPORTE_OK,
        CASE
            WHEN O.REPOTE_TEMPO_HABIL IS NULL THEN 'SIM'
            ELSE O.REPOTE_TEMPO_HABIL
        END AS REPORTE_TEMPOHABIL,
        CASE
            WHEN O.STATUS LIKE '%PREST%' OR O.STATUS LIKE '%CNICO%' THEN 'NO-SHOW TÉCNICO'
            WHEN O.STATUS LIKE '%Prestador%' THEN 'NO-SHOW TÉCNICO'
            WHEN O.STATUS LIKE '%CLIENTE%' THEN 'NO-SHOW CLIENTE'
            WHEN O.STATUS LIKE '%Cliente%' THEN 'NO-SHOW CLIENTE'
            WHEN O.STATUS LIKE '%COBLI%' THEN 'NO-SHOW COBLI'
            WHEN O.STATUS LIKE '%Cobli%' THEN 'NO-SHOW COBLI'
            ELSE 'CONCLUÍDA'
        END AS STATUS,
        REPLACE(REPLACE(P.NOME, '%20', ' '), '%26', '&') AS PRESTADOR
        
    FROM
        SUPPLY.SUPPLY_DRIVER_INSTALLER.OS_FINALIZADAS AS O
    LEFT JOIN
        SUPPLY.SUPPLY_DRIVER_INSTALLER.EVENTOS AS E
        ON 
        O.ORDEM_DE_SERVICO = E.ORDEM_DE_SERVICO
    LEFT JOIN
        SUPPLY.SUPPLY_DRIVER_INSTALLER.PRESTADORES_APP AS P
        ON 
        E.PRESTADOR = P.ID
    WHERE
        DATA_SERVICO >= '2024-05-01'
),

--- QUERY PRESTADOR X ORDEM ---

ORDEM_PRESTADOR AS (
    SELECT
        REPLACE(E.ORDEM_DE_SERVICO, ' ', '') AS ORDEM_DE_SERVICO,
        P.NOME AS PRESTADOR
    FROM
        SUPPLY.SUPPLY_DRIVER_INSTALLER.EVENTOS AS E
    LEFT JOIN
        SUPPLY.SUPPLY_DRIVER_INSTALLER.PRESTADORES_APP AS P
        ON E.PRESTADOR = P.ID
),

--- [QUERY - BASE DE PRESTADOR X CONSULTOR] ---

PRESTADOR AS (
    SELECT
        NOME_FANTASIA AS PRESTADOR,
        CASE
            WHEN NOME_RESPONSAVEL IS NULL THEN 'SEM CONSULTOR'
            ELSE NOME_RESPONSAVEL
        END AS CONSULTOR,
        UF
    FROM
        SUPPLY.SUPPLY_DRIVER_INSTALLER.REDE_CREDENCIADA
),

--- [QUERY - IQP DADOS COMPILADOS] ---

IQP AS (
    SELECT
        REPLACE(OS.ORDEM_DE_SERVICO, ' ', '') AS ORDEM_DE_SERVICO,
        OS.ID_AGENDAMENTO,
        OS.DATA_SERVICO,
        OS.REPORTE_OK,
        OS.REPORTE_TEMPOHABIL,
        OS.STATUS,
        DISP.ESN,
        DISP.TIPO_SERVICO,
        OP.PRESTADOR,
        PREST.UF,
        PREST.CONSULTOR,
        CASE
            WHEN DISP.TIPO_SERVICO = 'DESINSTALAÇÃO' THEN 0
            ELSE COUNT(DISTINCT TEST.ESN)
        END AS TESTE_REALIZADO
    FROM
        ORDENS AS OS
    FULL JOIN
        DISPOSITIVOS AS DISP
            ON
            OS.ORDEM_DE_SERVICO = DISP.ORDEM_DE_SERVICO AND
            OS.DATA_SERVICO = DISP.DATA_SERVICO
    FULL JOIN
        TESTES AS TEST
            ON
            DISP.ESN = TEST.ESN AND
            DATEDIFF('DAY',TEST.DATA_TESTE, DISP.DATA_SERVICO) BETWEEN 0 AND 5
    FULL JOIN
        ORDEM_PRESTADOR AS OP
        ON
        OP.ORDEM_DE_SERVICO = OS.ORDEM_DE_SERVICO
    FULL JOIN
        PRESTADOR AS PREST
            ON
            PREST.PRESTADOR = OP.PRESTADOR
    GROUP BY
        OS.ORDEM_DE_SERVICO,
        OS.ID_AGENDAMENTO,
        OS.DATA_SERVICO,
        OS.REPORTE_OK,
        OS.REPORTE_TEMPOHABIL,
        OS.STATUS,
        DISP.ESN,
        DISP.TIPO_SERVICO,
        OP.PRESTADOR,
        PREST.UF,
        PREST.CONSULTOR
),

--- [QUERY DE DADOS AGREGADOS] ---

RESUMO_IQP AS (
    SELECT
        REPLACE(ORDEM_DE_SERVICO, ' ', '') AS ORDEM_DE_SERVICO,
        DATA_SERVICO,
        STATUS,
        REPORTE_OK,
        REPORTE_TEMPOHABIL,
        PRESTADOR,
        UF,
        CONSULTOR,
    
 --- [MODELAGEM - QUANTIDADES] ---
    
        SUM(CASE WHEN TIPO_SERVICO = 'INSTALAÇÃO' THEN 1 ELSE 0 END) AS QTD_INSTALACAO,
        SUM(CASE WHEN TIPO_SERVICO = 'DESINSTALAÇÃO' THEN 1 ELSE 0 END) AS QTD_DESINSTALACAO,
        SUM(CASE WHEN TIPO_SERVICO = 'VISITA TÉCNICA' THEN 1 ELSE 0 END) AS QTD_VISITA_TECNICA,
        SUM(CASE WHEN TIPO_SERVICO <> 'DESINSTALAÇÃO' THEN 1 ELSE 0 END) AS QTD_NECESSIDADE_TESTE,
    
 --- [QUANTIDADE DE DISPOSITIVOS TESTADOS] ---
    
        SUM(TESTE_REALIZADO) AS QTD_TESTADO
    FROM
        IQP
    GROUP BY
        ORDEM_DE_SERVICO,
        DATA_SERVICO,
        STATUS,
        REPORTE_OK,
        REPORTE_TEMPOHABIL,
        PRESTADOR,
        UF,
        CONSULTOR
),

--- [DEFINIÇÃO VALORES MÉTRICAS] ---

VAL_IQP AS (
    SELECT
        ORDEM_DE_SERVICO,
        DATA_SERVICO,
        STATUS,
        REPORTE_OK,
        REPORTE_TEMPOHABIL,
        PRESTADOR,
        UF,
        CONSULTOR,
        QTD_INSTALACAO,
        QTD_DESINSTALACAO,
        QTD_VISITA_TECNICA,
        QTD_NECESSIDADE_TESTE,
        QTD_TESTADO,
        CASE
            WHEN QTD_NECESSIDADE_TESTE = 0 THEN 1
            ELSE ROUND(QTD_TESTADO / QTD_NECESSIDADE_TESTE, 1)
        END AS ADERENCIA_TESTES,
        CASE
            WHEN REPORTE_OK = 'SIM' THEN 1
            ELSE 0
        END AS VALOR_REPORTE_OK,
        CASE
            WHEN REPORTE_TEMPOHABIL = 'SIM' THEN 1
            ELSE 0
        END AS VALOR_REPORTE_TEMPOHABIL
    FROM
        RESUMO_IQP
)
SELECT
    ORDEM_DE_SERVICO,
    DATA_SERVICO,
    STATUS,
    REPORTE_OK,
    REPORTE_TEMPOHABIL,
    PRESTADOR,
    UF,
    CONSULTOR,
    QTD_INSTALACAO,
    QTD_DESINSTALACAO,
    QTD_VISITA_TECNICA,
    QTD_NECESSIDADE_TESTE,
    QTD_TESTADO,
    ADERENCIA_TESTES,

--- [CALCULO DAS METRICAS DO SCORE] ---

    (
    (ADERENCIA_TESTES *                                               
        CASE WHEN STATUS = 'NO-SHOW TÉCNICO' THEN 0 ELSE 0.6 END) + --- ADERENCIA TESTES
    (VALOR_REPORTE_OK *                                               
        CASE WHEN STATUS = 'NO-SHOW TÉCNICO' THEN 0 ELSE 0.2 END) + --- REPORTE OK
    (VALOR_REPORTE_TEMPOHABIL *                                       
        CASE WHEN STATUS = 'NO-SHOW TÉCNICO' THEN 0 ELSE 0.2 END)  --- REPORTE EM TEMPO HABIL
    ) AS SCORE
FROM
    VAL_IQP
WHERE
    ORDEM_DE_SERVICO IS NOT NULL
ORDER BY
    DATA_SERVICO
)
